return {}
-- return {
--   'folke/trouble.nvim',
--   opts = {
--     focus = true,
--   },
--   cmd = 'Trouble',
--   keys = {
--     {
--       '<leader>pd',
--       '<cmd>Trouble diagnostics toggle<cr>',
--       desc = 'Diagnostics (Trouble)',
--     },
--     {
--       '<leader>cs',
--       '<cmd>Trouble symbols toggle<cr>',
--       desc = 'Symbols (Trouble)',
--     },
--     {
--       '<leader>cl',
--       '<cmd>Trouble lsp toggle focus=false win.position=right<cr>',
--       desc = 'LSP Definitions / references / ... (Trouble)',
--     },
--
--     {
--       'gr',
--       '<cmd>Trouble lsp_references toggle<cr>',
--       desc = 'LSP References (Trouble)',
--     },
--
--     {
--       'gd',
--       '<cmd>Trouble lsp_definitions toggle<cr>',
--       desc = 'LSP Definitions (Trouble)',
--     },
--   },
--   init = function()
--     vim.api.nvim_create_autocmd('BufLeave', {
--       pattern = '*',
--       callback = function()
--         if vim.bo.filetype == 'trouble' then
--           vim.cmd 'close'
--         end
--       end,
--     })
--   end,
-- }
