include theme.conf

# linux_display_server x11
# linux_display_server wayland

# hide_window_decorations titlebar-only

# wayland_titlebar_color background

font_family             Menlo Nerd Font Mono

# modify_font cell_height -1px
# modify_font cell_width 1px
font_size               10.6
disable_ligatures       always
window_padding_width    0

cursor_text_color       background
selection_foreground    none
selection_background    none
selection_style         reverse
# background_opacity 0.9
remember_window_size    no
initial_window_width    120c
initial_window_height   40c
enable_audio_bell       no
#confirm_os_window_close 0

scrollback_lines        10000

# --- Scrolling Settings ---
# touch_scroll_multiplier 30.0
# wheel_scroll_multiplier 5.0
