return {}
-- return {
-- 	"hrsh7th/nvim-cmp",
-- 	version = false, -- last release is way too old
-- 	event = "InsertEnter",
-- 	dependencies = {
-- 		"hrsh7th/cmp-nvim-lsp",
-- 		"hrsh7th/cmp-buffer",
-- 		"hrsh7th/cmp-path",
-- 	},
-- 	opts = function()
-- 		-- Register nvim-cmp lsp capabilities
-- 		vim.lsp.config("*", { capabilities = require("cmp_nvim_lsp").default_capabilities() })
--
-- 		vim.api.nvim_set_hl(0, "CmpGhostText", { link = "Comment", default = true })
-- 		local cmp = require("cmp")
-- 		local defaults = require("cmp.config.default")()
-- 		local auto_select = true
-- 		return {
-- 			completion = {
-- 				completeopt = "menu,menuone,noinsert" .. (auto_select and "" or ",noselect"),
-- 				autocomplete = false, -- Disable automatic completion popup
-- 			},
-- 			preselect = auto_select and cmp.PreselectMode.Item or cmp.PreselectMode.None,
-- 			mapping = cmp.mapping.preset.insert({
-- 				["<C-b>"] = cmp.mapping.scroll_docs(-4),
-- 				["<C-f>"] = cmp.mapping.scroll_docs(4),
-- 				["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
-- 				["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
-- 				["<C-Space>"] = cmp.mapping.complete(),
-- 				["<CR>"] = cmp.mapping.confirm({ select = auto_select }),
-- 				["<C-y>"] = cmp.mapping.confirm({ select = true }),
-- 				["<S-CR>"] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
-- 				["<C-CR>"] = function(fallback)
-- 					cmp.abort()
-- 					fallback()
-- 				end,
-- 				["<Tab>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
-- 				["<S-Tab>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
-- 			}),
-- 			sources = cmp.config.sources({
-- 				{ name = "nvim_lsp" },
-- 				{ name = "path" },
-- 			}, {
-- 				{ name = "buffer" },
-- 			}),
-- 			formatting = {
-- 				format = function(entry, item)
-- 					-- Define completion kind icons
-- 					local icons = {
-- 						Text = "󰉿",
-- 						Method = "󰆧",
-- 						Function = "󰊕",
-- 						Constructor = "",
-- 						Field = "󰜢",
-- 						Variable = "󰀫",
-- 						Class = "󰠱",
-- 						Interface = "",
-- 						Module = "",
-- 						Property = "󰜢",
-- 						Unit = "󰑭",
-- 						Value = "󰎠",
-- 						Enum = "",
-- 						Keyword = "󰌋",
-- 						Snippet = "",
-- 						Color = "󰏘",
-- 						File = "󰈙",
-- 						Reference = "󰈇",
-- 						Folder = "󰉋",
-- 						EnumMember = "",
-- 						Constant = "󰏿",
-- 						Struct = "󰙅",
-- 						Event = "",
-- 						Operator = "󰆕",
-- 						TypeParameter = "",
-- 					}
--
-- 					if icons[item.kind] then
-- 						item.kind = icons[item.kind] .. " " .. item.kind
-- 					end
--
-- 					local widths = {
-- 						abbr = vim.g.cmp_widths and vim.g.cmp_widths.abbr or 40,
-- 						menu = vim.g.cmp_widths and vim.g.cmp_widths.menu or 30,
-- 					}
--
-- 					for key, width in pairs(widths) do
-- 						if item[key] and vim.fn.strdisplaywidth(item[key]) > width then
-- 							item[key] = vim.fn.strcharpart(item[key], 0, width - 1) .. "…"
-- 						end
-- 					end
--
-- 					return item
-- 				end,
-- 			},
-- 			experimental = {
-- 				ghost_text = false,
-- 			},
-- 			sorting = defaults.sorting,
-- 		}
-- 	end,
-- }
