-- return {
--   'Mofiqul/vscode.nvim',
--   priority = 1000,
--   config = function()
--     local vscode = require 'vscode'
--     local c = require('vscode.colors').get_colors()
--
--     vscode.setup {
--       -- Alternatively set style in setup
--       style = 'dark',
--       transparent = false,
--       italic_comments = false,
--       underline_links = true,
--       disable_nvimtree_bg = true,
--       terminal_colors = true,
--       color_overrides = {
--         vscLineNumber = '#FFFFFF',
--       },
--       group_overrides = {
--         -- this supports the same val table as vim.api.nvim_set_hl
--         -- use colors from this colorscheme by requiring vscode.colors!
--         Cursor = { fg = c.vscDarkBlue, bg = c.vscLightGreen, bold = true },
--       },
--     }
--     vim.cmd.colorscheme 'vscode'
--   end,
-- }

return {}
